# Webhook 服务器配置
server:
  port: 8080
  timeout: 30
bot:
  qq:
    enable: false
    id: appid
    uid: qq
    secret: secret
    token: token
    type: public
    sandbox: false
    webhook_path: /qq
  telegram:
    enable: false
    token: token
  kook:
    enable: false
    token: token
# 日志配置
logging:
  level: info
  file_path: ./webhook.log
  add_source: true
  json: false
channels:
  - ws-reverse:
      universal: "url"
      reconnect-interval: 3000
      authorization:
      retry-delay: 0
      max-retries: 0
  - ws:
      address: 0.0.0.0:8080
      authorization: