name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git version
          git clone "${{ github.event.repository.html_url }}" /home/runner/work/GoQHttp/GoQHttp
          git checkout "${{ github.ref }}"

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.1'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}